### PR TITLE
Update WebUntisRequestManager.java

### PR DESCRIPTION
**Pull request by captnced2**
Removed two / from DEFAULT_ENDPOINT and anonymousLogin that made the resulting URL end up with two / and result in an error

### CODE REVIEW

**Comment by captnced2** [comment]
Nice Library btw, the only one for WebUntis in Java. Idk why it's not more popular

**Comment by Keule0010** [comment]
Thank you :) 
That's why I made the lib but I could have written it better.

Unfortunately I don't have access to a WebUntis account anymore and can't really test it. 
But I tried to recreate the error with another URL. I just put a second `/` inside the URL but everything worked just fine.
Can you show me the error?

It probably depends on the server URL whether you have two `/` or one.
WebUntisRequestManager.java:
`26		final URL url = new URL(session.getServer() + getEndPoint(endPoint) + "?school=" + school);`

So it would probably better to check in the `getEndPoint()` for a leading / and check that `getServer()` (or when setting the URL only once) returns a string with a trailing `/.`
I have also seen that the `new URL(str)` constructor is deprecated in Java 20. Would you mind to replace them with `new URI(str).toURL();`? Maybe this could fix the error. But I can do that too if I got them time.

**Comment by captnced2** [comment]
So the error i got was this:
`Server returned HTTP response code: 500 for URL: https://nessa.webuntis.com//WebUntis/jsonrpc_intern.do?school=school` (removed school for privacy)

I actually didn't really look into **why** this was happening a few days ago but i had to remove two `/` because i am using anonymous login. So the first error happens because the anonymous logins EndPoint has a leading `/` and the second because all other requests are using DEFAULT_ENDPOINT which also has a leading `/`.
Using `URI(str).toURL();` sadly didn't fix it.

Alright so i'll remove all leading `/` from all EndPoints i find and replace the URL constructor and then commit.

Also don't tell yourself your lib is bad :D, i mean it works (_almost_) perfectly while my stuff didn't D: and it's the only one in Java.

Edit: Just noticed the `secretLogin()` actually already has the correct endpoint

**Comment by Keule0010** [comment]
If you open the URL inside the browser you see the whole error message.
`Type Exception Report

Message The request was rejected because the URL contained a potentially malicious String "//"

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
	org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:369)
	org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:336)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:194)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	com.grupet.web.filter.Log4j2PropertiesPostFilter.doFilter(Log4j2PropertiesPostFilter.java:39)
	com.grupet.web.core.SessionFilter.doFilter(SessionFilter.java:100)
	com.grupet.web.filter.HttpMethodPreFilter.doFilter(HttpMethodPreFilter.java:46)
	com.grupet.web.filter.Log4j2PropertiesPreFilter.doFilter(Log4j2PropertiesPreFilter.java:81)
	org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
Note The full stack trace of the root cause is available in the server logs.`

Thank you again ;)

**Pull request merged**
